#!/usr/bin/env bash
# install haproxy and load balancing

sudo apt-get update
sudo apt-get install haproxy -y

echo "
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.145.34.233:80 check
    server web-02 18.212.77.139:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart